[project]
name = "mcp-server-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.12.3",
    "pytest>=8.4.1",
]

[dependency-groups]
dev = [
    "pytest-asyncio>=1.1.0",
]
